# Generated by Django 4.2.11 on 2024-05-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_alter_vendor_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='total_purchases',
            field=models.IntegerField(default=0, verbose_name='Total number of purchases'),
        ),
    ]
