# Generated by Django 4.2.11 on 2024-05-03 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0004_vendor_total_completed_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='total_completed_orders',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='total_purchases',
        ),
    ]
